#ifndef E36CD3DA_CBA9_4CC2_93ED_4CD5DDDC849A
#define E36CD3DA_CBA9_4CC2_93ED_4CD5DDDC849A



typedef enum { MAIN_PWR_ON_STBY_OK, MAIN_PWR_ON_STBY_LOW, MAIN_PWR_ON_STBY_DISCONNECTED, STBY_PWR_ON_MAIN_LOW,
               STBY_PWR_ON_MAIN_DISCONNECTED, CRITICAL_MAIN_POWERING, CRITICAL_STBY_POWERING } switching_states;

void switching_logic_loop();

#endif /* E36CD3DA_CBA9_4CC2_93ED_4CD5DDDC849A */
