#ifndef E36CD3DA_CBA9_4CC2_93ED_4CD5DDDC849A
#define E36CD3DA_CBA9_4CC2_93ED_4CD5DDDC849A



typedef enum { MAIN_PWR_ON_STBY_OK,
               MAIN_PWR_ON_STBY_LOW,
               STBY_PWR_ON_MAIN_LOW,
               MAIN_PWR_ON_STBY_DISCONNECT_OR_BAD_CONTACT,
               STBY_PWR_ON_MAIN_DISCONNECTED_OR_BAD_CONTACT,
               MAIN_PWR_ON_MAIN_BAD_CONTACT,
               STBY_PWR_ON_STBY_BAD_CONTACT,
               CRITICAL_MAIN_LOW_STBY_LOW,
               CRITICAL_MAIN_LOW_STBY_DISCONNECT_OR_BAD_CONTACT,
               CRITICAL_STBY_LOW_MAIN_DISCONNECT_OR_BAD_CONTACT,
               CRITICAL_MAIN_DISCONNECT_OR_BAD_CONTACT_STBY_DISCONNECT_OR_BAD_CONTACT
               } switching_states;

void switching_logic_loop();

#endif /* E36CD3DA_CBA9_4CC2_93ED_4CD5DDDC849A */
